"""add full_name to users

Revision ID: 15c979576760
Revises: 0407d8696171
Create Date: 2026-04-19 03:31:46.693458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15c979576760'
down_revision: Union[str, Sequence[str], None] = '0407d8696171'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add as nullable first so existing rows don't violate NOT NULL
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))
    # Backfill existing rows with an empty string
    op.execute("UPDATE users SET full_name = '' WHERE full_name IS NULL")
    # Now enforce NOT NULL
    op.alter_column('users', 'full_name', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
